### ISSUE TITLE
Navigation component failing to find navigation destination

### ISSUE THREAD

**Issue by jm47895** [jm47895/Lendsum#19]
So this probably has to do with [https://medium.com/halcyon-mobile/tackling-the-illegalargumentexception-navigation-destination-foo-is-unknown-to-this-89091d955c3c](this)

2020-11-15 00:23:26.066 7929-7929/com.lendsumapp.lendsum E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lendsumapp.lendsum, PID: 7929
    java.lang.IllegalArgumentException: Navigation action/destination com.lendsumapp.lendsum:id/action_chatRoomFragment_to_messagesFragment cannot be found from the current destination Destination(com.lendsumapp.lendsum:id/messagesFragment) label=MessagesFragment class=com.lendsumapp.lendsum.ui.ChatRoomsFragment
        at androidx.navigation.NavController.navigate(NavController.java:931)
        at androidx.navigation.NavController.navigate(NavController.java:868)
        at androidx.navigation.NavController.navigate(NavController.java:854)
        at androidx.navigation.NavController.navigate(NavController.java:842)
        at com.lendsumapp.lendsum.ui.MessagesFragment.onClick(MessagesFragment.kt:134)
        at android.view.View.performClick(View.java:6892)
        at android.view.View$PerformClick.run(View.java:26104)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by jm47895** [comment]
This issue has not happened within the past 25 days. Closing but will reopen if it happens again.
