### ISSUE TITLE
Login Fragment not attached to activity

### ISSUE THREAD

**Issue by jm47895** [jm47895/Lendsum#22]
2020-11-15 02:51:56.202 30012-30012/com.lendsumapp.lendsum E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lendsumapp.lendsum, PID: 30012
    java.lang.IllegalStateException: Fragment LoginFragment{c0bf2c7} (b1c04874-6cbd-41e9-93a9-82ff7ba0c290)} not attached to Activity
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1420)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1396)
        at com.lendsumapp.lendsum.ui.LoginFragment.onClick(LoginFragment.kt:154)
        at android.view.View.performClick(View.java:7858)
        at android.widget.TextView.performClick(TextView.java:15004)
        at android.view.View.performClickInternal(View.java:7831)
        at android.view.View.access$3600(View.java:879)
        at android.view.View$PerformClick.run(View.java:29359)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by jm47895** [comment]
Steps to reproduce: Go to edit profile screen -> type in things -> touch any part of the screen that is not the soft keyboard

**Comment by jm47895** [comment]
I think I solved this by changing how Nav host fragment is initialized and accessed using android x. Will re-open if it happens again.
